### ISSUE TITLE
Improvement : Try to follow "Graceful degradation" guidelines

### ISSUE THREAD

**Issue by Zardoz89** [salvadorsru/searchable-select#1]
Improvement : Try to follow "Graceful degradation" guidelines

## What means ?
That if an user loads a page with a browser that don't support web components (or with javascript disabled),  fallback to hide the `<input type=text>` and show only the `<select>`.

## Why?
Not everyone would be running the last browser on a modern computer or device. Some people would be running on old devices, and would be limited to a pure text browser. "Graceful degradation" aims to build a modern website/application that will work in the newest browsers, but falls back to an experience that while not as good still delivers essential content and functionality in older browsers.

## How??
Simple. Add the "hidden" attribute from javascript, not from pregenerated HTML. Add the `<input type=text />` using JavaScript. If a browser can't use webcomponents or run javascript, the users would only see a simple `<select>`  and forms would keep working fine.

Usage would be something like : 

```
      <searchable-select aria-label="Search countries" placeholder="Where are you from?">
        <select name="countries" >
          <option value="1">Argentina</option>
          <option value="2">Brazil</option>
          <option value="3">Canada</option>
          <option value="4">France</option>
          <option value="5">Germany</option>
          <option value="6">Japan</option>
        </select>
      </searchable-select>
```

## See

- https://developer.mozilla.org/en-US/docs/Glossary/Graceful_degradation
- https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement

**Comment by salvadorsru** [comment]
Hello,

Part of the functionality was already implemented, such as the dynamic generation of the input when it did not exist.

However, in line with your suggestion, I have added and slightly modified the component so that the select element also works in cases where JavaScript is disabled. Additionally, I have included the option to specify the attributes of the search input from the custom element.

I have improved the README by explaining how it would function in scenarios without JavaScript and documenting the variables that allow for component customization.

I greatly appreciate your feedback and would be delighted to receive more suggestions.

**Comment by Zardoz89** [comment]
Thanks!
I would take a look at it when I have time. I'm considering your webcomponent to replace the usage that I do of choosen.js

**Comment by Zardoz89** [comment]
Well, I did some more minor tests  : 

- Don't support <optgroup>
- Don't preserves <option> class attribute
- Don't supports multiple

I would try to get time and see if I could write code to add this functionality. IMO your small webcomponet have the potential to be a good replacement of  [harvesthq/chosen](harvesthq/chosen) / [ JJJ/chosen](/JJJ/chosen) that is un-mantined, and needs jQuery to work
